### ISSUE TITLE
404 When Scraping

### ISSUE THREAD

**Issue by KeeJef** [BasouKazuma/surveyplanet-scraper#1]
Followed instructions and am getting 

```
StatusCodeError: 404 - {"status":404,"url":"/v1/answers/summary/5e70270eb3ee9631d499d045","query":{"_":"1585199328889"},"type":"not_found","message":"The requested item does not exist."}
    at new StatusCodeError (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (C:\Users\Potter\Desktop\surveyplanet-scraper\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - {"status":404,"url":"/v1/answers/summary/5e70270eb3ee9631d499d045","query":{"_":"1585199328889"},"type":"not_found","message":"The requested item does not exist."}',
```

Maybe changes in the Survey Planet API

**Comment by mrtztg** [comment]
You can use this tool:
https://github.com/mrtztg/surveyplanet_result_export
